Update bash_util_funcs

diff --git a/bash_util_funcs b/bash_util_funcs
--- a/bash_util_funcs
+++ b/bash_util_funcs
@@ -11,3 +11,42 @@ function giignode() {
 function mkcdir() {
     mkdir -p "$1" && cd "$1"
 }
+
+# don't judge
+function gitlazy() {
+  git add .
+  git commit -a -m "$1"
+  git push
+}
+
+# Opens the github page for the current git repository in your browser 
+function gh() {
+   giturl=$(git config --get remote.origin.url)
+   if [ "$giturl" == "" ]
+       then
+         echo "Not a git repository or no remote.origin.url set"
+         exit 1;
+   fi
+
+  giturl=${giturl/git\@github\.com\:/https://github.com/}
+  giturl=${giturl/\.git/\/tree/}
+  branch="$(git symbolic-ref HEAD 2>/dev/null)" ||
+  branch="(unnamed branch)"     # detached HEAD
+  branch=${branch##refs/heads/}
+  giturl=$giturl$branch
+  open $giturl
+}
+
+# mkdirs before touch
+mktouch() {
+    if [ $# -lt 1 ]; then
+        echo "Missing argument";
+        return 1;
+    fi
+
+    for f in "$@"; do
+        mkdir -p -- "$(dirname -- "$f")"
+        touch -- "$f"
+    done
+}
+
